# Generated by Django 5.0.2 on 2024-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0002_alter_recipe_options_recipe_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
