# Generated by Django 5.0.2 on 2024-02-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0006_alter_recipe_options_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
